spring:
  #datasource
  datasource:
    username: ENC(Gx6RJkmSAi0m2tereEDuyg==)
    password: ENC(l3/1Rn5LVtnR55aoP3Q0MQ==)
    url: jdbc:mysql://120.27.24.193:3306/edu-eat-order?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: edu-eat-order
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  # view
  freemarker:
    prefix:
    suffix: .ftl
    template-loader-path: ["classpath:/templates/"]
    settings:
      number_format: '0.##'   #数字格式化，无小数点
server:
  port: 80


#log
logging:
  config: classpath:logback-spring.xml

# mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# mapper
mapper:
  enum-as-simple-type: true

# 加密配置
jasypt:
  encryptor:
    password: /NNiLvve/n/1LF5ol7dZdA==asdawcsdgsdsdasfw

## 自定义配置
zhibi:
  generate:
    packageConfig:
      parent: edu.eat.order
    strategy:
      sync: entity_to_database
    global:
      generatorFile: false
